# Generated by Django 5.0 on 2026-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=rfscVS0vtbw'),
            preserve_default=False,
        ),
    ]
