# Generated by Django 5.0 on 2026-03-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_videoprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
