# Generated by Django 5.0 on 2026-03-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_purchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(max_length=20),
        ),
    ]
