# Generated by Django 5.0 on 2026-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_video_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(max_length=50),
        ),
    ]
